package ui.prop;

import controladores.ControladorLogin;
import controladores.VistaLogin;
import javax.swing.JOptionPane;
import logica.dominio.Administrador;
import logica.dominio.Propietario;
import logica.sistema.Fachada;

public class LoginProp extends javax.swing.JDialog implements VistaLogin {

  private ControladorLogin controlador;

  /**
   * Creates new form LoginPropietario
   *
   * @param parent
   * @param modal
   */
  public LoginProp(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(null);
    this.controlador = new ControladorLogin(this);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    LoginPropUser = new javax.swing.JTextField();
    LoginPropBtn = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    LoginPropPass = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("ACCEDER");

    jLabel1.setText("Cédula:");

    jLabel2.setText("Contraseña:");

    LoginPropUser.setToolTipText("");

    LoginPropBtn.setText("INGRESAR");
    LoginPropBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        LoginPropBtnActionPerformed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("INGRESO A PROPIETARIOS DE VEHÍCULOS");

    jLabel21.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/img/cvu-icon.png"))); // NOI18N

    LoginPropPass.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        LoginPropPassActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout =
        new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          Short.MAX_VALUE)
                            .addComponent(
                                LoginPropBtn,
                                javax.swing.GroupLayout.Alignment.LEADING,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.LEADING,
                                layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.LEADING)
                                                  .addComponent(jLabel2)
                                                  .addComponent(jLabel1))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle
                                            .ComponentPlacement.UNRELATED)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout
                                                    .Alignment.LEADING,
                                                false)
                                            .addComponent(
                                                LoginPropUser,
                                                javax.swing.GroupLayout
                                                    .DEFAULT_SIZE,
                                                309, Short.MAX_VALUE)
                                            .addComponent(LoginPropPass))))
                    .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                          .addGap(202, 202, 202)
                          .addComponent(jLabel21)
                          .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                           Short.MAX_VALUE)));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jLabel21)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addGap(32, 32, 32)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(LoginPropUser,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          32, Short.MAX_VALUE))
                    .addGap(18, 18, Short.MAX_VALUE)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                LoginPropPass,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 30,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addComponent(LoginPropBtn,
                                  javax.swing.GroupLayout.DEFAULT_SIZE, 33,
                                  Short.MAX_VALUE)
                    .addGap(26, 26, 26)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void LoginPropPassActionPerformed(
      java.awt.event
          .ActionEvent evt) { // GEN-FIRST:event_LoginPropPassActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_LoginPropPassActionPerformed

  private void LoginPropBtnActionPerformed(java.awt.event.ActionEvent evt) {
    if (!LoginPropUser.getText().equals("") ||
        !LoginPropPass.getText().equals("")) {
      controlador.validarLoginProp(Integer.parseInt(LoginPropUser.getText()),
                                   LoginPropPass.getText());
    } else {
      error("Ingrese valores");
    }
  }

  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton LoginPropBtn;
  private javax.swing.JPasswordField LoginPropPass;
  private javax.swing.JTextField LoginPropUser;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel3;
  // End of variables declaration//GEN-END:variables

  @Override
  public void loginAdminValidado(Administrador a) {
    throw new UnsupportedOperationException(
        "Not supported yet."); // Generated from
                               // nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
  }

  @Override
  public void error(String message) {
    JOptionPane.showMessageDialog(this, message);
  }

  @Override
  public void loginPropValidado(Propietario p) {
    new TableroControlProp(null, false, p).setVisible(true);
    this.dispose();
  }
}
