package ui.prop;

import controladores.ControladorTableroControl;
import controladores.VistaTableroControl;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.table.DefaultTableModel;
import logica.dominio.Asignacion;
import logica.dominio.Notificacion;
import logica.dominio.Propietario;
import logica.dominio.Recarga;
import logica.dominio.Transito;
import logica.dominio.Vehiculo;
import logica.sistema.Fachada;

public class TableroControlProp
        extends javax.swing.JDialog implements VistaTableroControl {

    private Propietario propietario;
    private ControladorTableroControl controlador;

    public TableroControlProp(java.awt.Frame parent, boolean modal,
            Propietario p) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        propietario = p;
        controlador = new ControladorTableroControl(this, p);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaVehiculo = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTablaBonif = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTablaTransito = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        JTablaRecarga = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        JTablaNotificaciones = new javax.swing.JTable();
        CerrarSesionPropBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BorrarNotPropBtn = new javax.swing.JButton();
        RecargarPropBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JCantNotif = new javax.swing.JLabel();
        JNombre = new javax.swing.JLabel();
        JSaldo = new javax.swing.JLabel();
        JCantVehiculos = new javax.swing.JLabel();
        JCantBonif = new javax.swing.JLabel();
        JCantTrans = new javax.swing.JLabel();
        JCantRec = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TABLERO DE CONTROL");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N

        JTablaVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTablaVehiculo);

        JTablaBonif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(JTablaBonif);

        JTablaTransito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(JTablaTransito);

        JTablaRecarga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(JTablaRecarga);

        JTablaNotificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(JTablaNotificaciones);

        CerrarSesionPropBtn.setText("CERRAR SESIÓN");
        CerrarSesionPropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionPropBtnActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/money.png"))); // NOI18N

        BorrarNotPropBtn.setText("Borrar");
        BorrarNotPropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarNotPropBtnActionPerformed(evt);
            }
        });

        RecargarPropBtn.setText("Recargar");
        RecargarPropBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecargarPropBtnActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/car.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coupon.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/toll.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("VEHICULOS REGISTRADOS");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BONIFICACIONES ASIGNADAS");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setText("TRÁNSITOS REALIZADOS");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("RECARGAS REALIZADAS");

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel10.setText("NOTIFICACIONES");

        JCantNotif.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        JCantNotif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JCantNotif.setText("0");

        JNombre.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        JNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        JSaldo.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        JSaldo.setText("$ 0");

        JCantVehiculos.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        JCantVehiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JCantVehiculos.setText("0");

        JCantBonif.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        JCantBonif.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JCantBonif.setText("0");

        JCantTrans.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        JCantTrans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JCantTrans.setText("0");

        JCantRec.setFont(new java.awt.Font("Lucida Grande", 1, 36)); // NOI18N
        JCantRec.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JCantRec.setText("0");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/charging-station.png"))); // NOI18N

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ringing.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cvu-icon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(JSaldo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(JNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(BorrarNotPropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(JCantNotif)))
                                            .addComponent(jLabel10)))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCantBonif))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(JCantTrans))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(RecargarPropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(JCantRec)))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JCantVehiculos)
                                .addGap(8, 8, 8)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CerrarSesionPropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JSaldo)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JNombre)
                        .addComponent(jLabel1)))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(JCantVehiculos))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(JCantBonif)
                                .addGap(10, 10, 10))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JCantTrans)
                            .addGap(4, 4, 4)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JCantRec)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RecargarPropBtn)
                                .addGap(23, 23, 23))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JCantNotif)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BorrarNotPropBtn)))
                        .addGap(30, 30, 30)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CerrarSesionPropBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BorrarNotPropBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarNotPropBtnActionPerformed
        controlador.borrarNotificaciones();
    }//GEN-LAST:event_BorrarNotPropBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        controlador.salir();
    }//GEN-LAST:event_formWindowClosed

    private void RecargarPropBtnActionPerformed(
            java.awt.event.ActionEvent evt) { // GEN-FIRST:event_RecargarPropBtnActionPerformed
        // TODO add your handling code here:
        new RecargaProp(null, true, propietario).setVisible(true);
    } // GEN-LAST:event_RecargarPropBtnActionPerformed

    private void CerrarSesionPropBtnActionPerformed(java.awt.event.ActionEvent evt) {
        controlador.salir();
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarNotPropBtn;
    private javax.swing.JButton CerrarSesionPropBtn;
    private javax.swing.JLabel JCantBonif;
    private javax.swing.JLabel JCantNotif;
    private javax.swing.JLabel JCantRec;
    private javax.swing.JLabel JCantTrans;
    private javax.swing.JLabel JCantVehiculos;
    private javax.swing.JLabel JNombre;
    private javax.swing.JLabel JSaldo;
    private javax.swing.JTable JTablaBonif;
    private javax.swing.JTable JTablaNotificaciones;
    private javax.swing.JTable JTablaRecarga;
    private javax.swing.JTable JTablaTransito;
    private javax.swing.JTable JTablaVehiculo;
    private javax.swing.JButton RecargarPropBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public Propietario getPropietario() {
        return propietario;
    }

    @Override
    public void mostrarTransito(ArrayList<Transito> transitos) {
        if (transitos != null) {
            DefaultTableModel datos = new DefaultTableModel();
            datos.addColumn("Puesto");
            datos.addColumn("Matricula");
            datos.addColumn("Tarifa");
            datos.addColumn("Tarifa(monto)");
            datos.addColumn("Bonificacion");
            datos.addColumn("Bonificacion(monto)");
            datos.addColumn("Monto pagado");
            datos.addColumn("Fecha");

            datos.setRowCount(transitos.size());

            int fila = 0;

            DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            for (Transito transito : transitos) {
                if (transito.getAsignacion() != null) {
                    datos.setValueAt(transito.getAsignacion().getBonificacion().getNombre(), fila, 4);
                } else {
                    datos.setValueAt("", fila, 4);
                }
                datos.setValueAt(transito.getPuesto().getNombre(), fila, 0);
                datos.setValueAt(transito.getVehiculo().getMatricula(), fila, 1);
                datos.setValueAt(transito.getVehiculo().getCategoria().getNombre(), fila, 2);
                datos.setValueAt(transito.getMonto(), fila, 3);
                datos.setValueAt(transito.getDescuento(), fila, 5);
                datos.setValueAt(transito.getTotal(), fila, 6);
                datos.setValueAt(transito.getFecha().format(dateTimeFormatter), fila, 7);
                fila = fila + 1;
            }

            JTablaTransito.setModel(datos);
        } else {
            JCantTrans.setText("0");
        }
    }

    @Override
    public void mostrarVehiculo(ArrayList<Vehiculo> vehiculos) {
        if (vehiculos != null) {
            DefaultTableModel datos = new DefaultTableModel();

            datos.addColumn("Matricula");
            datos.addColumn("Modelo");
            datos.addColumn("Color");
            datos.addColumn("# Transitos");
            datos.addColumn("Monto total");
            datos.setRowCount(vehiculos.size());
            int fila = 0;

            for (Vehiculo vehiculo : vehiculos) {
                datos.setValueAt(vehiculo.getMatricula(), fila, 0);
                datos.setValueAt(vehiculo.getModelo(), fila, 1);
                datos.setValueAt(vehiculo.getColor(), fila, 2);/////
                datos.setValueAt(vehiculo.getTransitos().size(), fila, 3);/////
                datos.setValueAt(vehiculo.getMontoTotal(), fila, 4);
                fila = fila + 1;
            }
            JTablaVehiculo.setModel(datos);

        } else {
            JCantVehiculos.setText("0");
        }
    }

    @Override
    public void mostrarNotificaciones(ArrayList<Notificacion> notificaciones) {
        if (notificaciones != null) {
            DefaultTableModel datos = new DefaultTableModel();
            datos.addColumn("Fecha");
            datos.addColumn("Mensaje");
            datos.setRowCount(notificaciones.size());
            int fila = 0;

            DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            for (Notificacion notificacion : notificaciones) {

                datos.setValueAt(notificacion.getFecha().format(dateTimeFormatter), fila, 0);
                datos.setValueAt(notificacion.getMensaje(), fila, 1);
                fila++;
            }

            JTablaNotificaciones.setModel(datos);
        } else {
            JCantNotif.setText("0");
        }
    }

    @Override
    public void mostrarBonificaciones(ArrayList<Asignacion> bonificaciones) {
        if (bonificaciones != null) {
            DefaultTableModel datos = new DefaultTableModel();
            datos.addColumn("Nombre bonificacion");
            datos.addColumn("Puesto");
            datos.addColumn("Fecha asignada");
            datos.setRowCount(bonificaciones.size());
            int fila = 0;

            DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            for (Asignacion asignacion : bonificaciones) {

                datos.setValueAt(asignacion.getBonificacion().getNombre(), fila, 0);
                datos.setValueAt(asignacion.getPuesto().getNombre(), fila, 1);
                datos.setValueAt(asignacion.getFecha().format(dateTimeFormatter), fila, 2);
                fila = fila + 1;
            }

            JTablaBonif.setModel(datos);
        } else {
            JCantBonif.setText("0");
        }
    }

    @Override
    public void mostrarRecargas(ArrayList<Recarga> recargas) {
        if (recargas != null) {
            DefaultTableModel datos = new DefaultTableModel();
            datos.addColumn("Fecha recarga");
            datos.addColumn("Monto");
            datos.addColumn("Estado");
            datos.addColumn("Administrador");

            datos.setRowCount(recargas.size());
            int fila = 0;

            for (Recarga recarga : recargas) {
                String estado = "Pendiente";
                String nombre = "";
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                datos.setValueAt(sdf.format(recarga.getFecha()), fila, 0);
                datos.setValueAt(recarga.getMonto(), fila, 1);

                if (recarga.getAdministrador() != null) {
                    estado = "Aprobado";
                    nombre = recarga.getAdministrador().getNombreCompleto();
                }
                datos.setValueAt(estado, fila, 2);
                datos.setValueAt(nombre, fila, 3);
                fila = fila + 1;
            }

            JTablaRecarga.setModel(datos);
        } else {
            JCantRec.setText("0");
        }
    }

    @Override
    public void mostrarDatosProp(Propietario propietario) {
        JNombre.setText(propietario.getNombreCompleto());
        JSaldo.setText("$ " + String.valueOf(propietario.getSaldo()));
    }

    @Override
    public void mostrarCantidadDatos(int cantVehiculos, int cantNotificaciones, int cantAsignaciones, int cantTransitos, int cantRecargas) {
        JCantTrans.setText(String.valueOf(cantTransitos));
        JCantVehiculos.setText(String.valueOf(cantVehiculos));
        JCantNotif.setText(String.valueOf(cantNotificaciones));
        JCantBonif.setText(String.valueOf(cantAsignaciones));
        JCantRec.setText(String.valueOf(cantRecargas));
    }
}
