package ui.admin;

import controladores.ControladorBonificaciones;
import controladores.VistaBonificacion;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.dominio.Administrador;
import logica.dominio.Asignacion;
import logica.dominio.Propietario;
import logica.dominio.Puesto;
import logica.sistema.TipoBonificacion;

public class BonificacionesAdmin
    extends javax.swing.JDialog implements VistaBonificacion {

  private Administrador admin;
  private ControladorBonificaciones controlador;
  private Propietario propietario;

  /**
   * Creates new form BonificacionesAdmin
   */
  public BonificacionesAdmin(java.awt.Frame parent, boolean modal,
                             Administrador admin) {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(null);
    this.admin = admin;
    this.controlador = new ControladorBonificaciones(this, this.admin);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    precargaDatos1 = new inicio.PrecargaDatos();
    precargaDatos2 = new inicio.PrecargaDatos();
    jLabel3 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    JComboBonif = new javax.swing.JComboBox<>();
    jLabel1 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    JCedula = new javax.swing.JTextField();
    JBuscar = new javax.swing.JToggleButton();
    JComboPuestos = new javax.swing.JComboBox<>();
    jLabel2 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jLabel5 = new javax.swing.JLabel();
    JNombre = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    JTablaBonif = new javax.swing.JTable();
    JAsignar = new javax.swing.JToggleButton();
    JBtnCerrar = new javax.swing.JButton();
    jMenuBar1 = new javax.swing.JMenuBar();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("CONSOLA DE ADMINISTRACIÓN");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosed(java.awt.event.WindowEvent evt) {
        formWindowClosed(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("ASIGNAR BONIFICACIÓN");

    jLabel21.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/img/cvu-icon.png"))); // NOI18N

    JComboBonif.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] {" "}));
    JComboBonif.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JComboBonifActionPerformed(evt);
      }
    });

    jLabel1.setText("Bonificaciones:");

    jLabel4.setText("Cédula:");

    JCedula.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JCedulaActionPerformed(evt);
      }
    });

    JBuscar.setText("BUSCAR");
    JBuscar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JBuscarActionPerformed(evt);
      }
    });

    JComboPuestos.setModel(
        new javax.swing.DefaultComboBoxModel<>(new String[] {" "}));

    jLabel2.setText("Puestos:");

    jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel5.setText("Propietario:");

    JNombre.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    JNombre.setText(" ");

    JTablaBonif.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {

        },
        new String[] {"Bonificación", "Puesto"}));
    jScrollPane1.setViewportView(JTablaBonif);

    JAsignar.setText("ASIGNAR");
    JAsignar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JAsignarActionPerformed(evt);
      }
    });

    JBtnCerrar.setText("CERRAR");
    JBtnCerrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JBtnCerrarActionPerformed(evt);
      }
    });
    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout =
        new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout.createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout
                                                    .Alignment.LEADING)
                                            .addComponent(
                                                jLabel3,
                                                javax.swing.GroupLayout
                                                    .Alignment.TRAILING,
                                                javax.swing.GroupLayout
                                                    .DEFAULT_SIZE,
                                                607, Short.MAX_VALUE)
                                            .addGroup(
                                                layout.createSequentialGroup()
                                                    .addComponent(jLabel21)
                                                    .addGap(0, 0,
                                                            Short.MAX_VALUE))))
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout
                                                    .Alignment.LEADING)
                                            .addGroup(
                                                layout
                                                    .createParallelGroup(
                                                        javax.swing.GroupLayout
                                                            .Alignment.TRAILING)
                                                    .addGroup(
                                                        layout
                                                            .createSequentialGroup()
                                                            .addComponent(
                                                                jLabel2)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(
                                                                JComboPuestos,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                382,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .PREFERRED_SIZE))
                                                    .addGroup(
                                                        layout
                                                            .createSequentialGroup()
                                                            .addGroup(
                                                                layout
                                                                    .createParallelGroup(
                                                                        javax
                                                                            .swing
                                                                            .GroupLayout
                                                                            .Alignment
                                                                            .TRAILING)
                                                                    .addComponent(
                                                                        jLabel4)
                                                                    .addComponent(
                                                                        jLabel1))
                                                            .addGroup(
                                                                layout
                                                                    .createParallelGroup(
                                                                        javax
                                                                            .swing
                                                                            .GroupLayout
                                                                            .Alignment
                                                                            .LEADING)
                                                                    .addGroup(
                                                                        layout
                                                                            .createSequentialGroup()
                                                                            .addGap(
                                                                                249,
                                                                                249,
                                                                                249)
                                                                            .addComponent(
                                                                                JBuscar,
                                                                                javax
                                                                                    .swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE,
                                                                                151,
                                                                                javax
                                                                                    .swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE))
                                                                    .addGroup(
                                                                        javax
                                                                            .swing
                                                                            .GroupLayout
                                                                            .Alignment
                                                                            .TRAILING,
                                                                        layout
                                                                            .createSequentialGroup()
                                                                            .addGap(
                                                                                18,
                                                                                18,
                                                                                18)
                                                                            .addGroup(
                                                                                layout
                                                                                    .createParallelGroup(
                                                                                        javax
                                                                                            .swing
                                                                                            .GroupLayout
                                                                                            .Alignment
                                                                                            .LEADING)
                                                                                    .addComponent(
                                                                                        JComboBonif,
                                                                                        javax
                                                                                            .swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE,
                                                                                        382,
                                                                                        javax
                                                                                            .swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE)
                                                                                    .addComponent(
                                                                                        JCedula,
                                                                                        javax
                                                                                            .swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE,
                                                                                        225,
                                                                                        javax
                                                                                            .swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE))))))
                                            .addComponent(
                                                jSeparator1,
                                                javax.swing.GroupLayout
                                                    .PREFERRED_SIZE,
                                                536,
                                                javax.swing.GroupLayout
                                                    .PREFERRED_SIZE)
                                            .addGroup(
                                                layout
                                                    .createParallelGroup(
                                                        javax.swing.GroupLayout
                                                            .Alignment.TRAILING,
                                                        false)
                                                    .addComponent(
                                                        JBtnCerrar,
                                                        javax.swing.GroupLayout
                                                            .DEFAULT_SIZE,
                                                        javax.swing.GroupLayout
                                                            .DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                    .addGroup(
                                                        javax.swing.GroupLayout
                                                            .Alignment.LEADING,
                                                        layout
                                                            .createSequentialGroup()
                                                            .addComponent(
                                                                jScrollPane1,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                338,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .PREFERRED_SIZE)
                                                            .addPreferredGap(
                                                                javax.swing
                                                                    .LayoutStyle
                                                                    .ComponentPlacement
                                                                    .RELATED)
                                                            .addComponent(
                                                                JAsignar,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .PREFERRED_SIZE,
                                                                151,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                          .addGap(210, 210, 210)
                                          .addComponent(jLabel5)
                                          .addPreferredGap(
                                              javax.swing.LayoutStyle
                                                  .ComponentPlacement.RELATED)
                                          .addComponent(JNombre)))
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel3)
                    .addGap(64, 64, 64)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                JComboBonif,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                    .addGap(22, 22, 22)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(
                                JComboPuestos,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                    .addGap(18, 18, 18)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBuscar)
                            .addComponent(
                                JCedula, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addComponent(jSeparator1,
                                  javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(layout
                                  .createParallelGroup(
                                      javax.swing.GroupLayout.Alignment.LEADING)
                                  .addComponent(jLabel5)
                                  .addComponent(JNombre))
                    .addGap(30, 30, 30)
                    .addGroup(layout
                                  .createParallelGroup(
                                      javax.swing.GroupLayout.Alignment.LEADING)
                                  .addComponent(
                                      jScrollPane1,
                                      javax.swing.GroupLayout.PREFERRED_SIZE,
                                      136,
                                      javax.swing.GroupLayout.PREFERRED_SIZE)
                                  .addComponent(JAsignar))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBtnCerrar,
                                  javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel21)
                    .addContainerGap()));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void
  JCedulaActionPerformed(java.awt.event.ActionEvent
                             evt) { // GEN-FIRST:event_JCedulaActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_JCedulaActionPerformed

  private void JComboBonifActionPerformed(
      java.awt.event
          .ActionEvent evt) { // GEN-FIRST:event_JComboBonifActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_JComboBonifActionPerformed

  private void JBtnCerrarActionPerformed(
      java.awt.event
          .ActionEvent evt) { // GEN-FIRST:event_JBtnCerrarActionPerformed
    this.dispose();
  } // GEN-LAST:event_JBtnCerrarActionPerformed

  private void formWindowClosed(
      java.awt.event.WindowEvent evt) { // GEN-FIRST:event_formWindowClosed
    controlador.salir();
  } // GEN-LAST:event_formWindowClosed

  private void
  JBuscarActionPerformed(java.awt.event.ActionEvent
                             evt) { // GEN-FIRST:event_JBuscarActionPerformed

    int cedula = Integer.parseInt(JCedula.getText());
    controlador.buscarPropietario(cedula);
  } // GEN-LAST:event_JBuscarActionPerformed

  private void
  JAsignarActionPerformed(java.awt.event.ActionEvent
                              evt) { // GEN-FIRST:event_JAsignarActionPerformed
    String nombrePuesto = (String)JComboPuestos.getSelectedItem();
    String tipoBonificacion = (String)JComboBonif.getSelectedItem();
    controlador.asignarBonificacion(propietario, nombrePuesto,
                                    tipoBonificacion);
  } // GEN-LAST:event_JAsignarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JToggleButton JAsignar;
  private javax.swing.JButton JBtnCerrar;
  private javax.swing.JToggleButton JBuscar;
  private javax.swing.JTextField JCedula;
  private javax.swing.JComboBox<String> JComboBonif;
  private javax.swing.JComboBox<String> JComboPuestos;
  private javax.swing.JLabel JNombre;
  private javax.swing.JTable JTablaBonif;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JMenuBar jMenuBar1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSeparator jSeparator1;
  private inicio.PrecargaDatos precargaDatos1;
  private inicio.PrecargaDatos precargaDatos2;
  // End of variables declaration//GEN-END:variables

  @Override
  public void mostrarBonificaciones(ArrayList<TipoBonificacion> tipos) {
    for (TipoBonificacion tb : tipos) {
      JComboBonif.addItem(tb.getNombre());
    }
  }

  @Override
  public void mostrarPuestos(ArrayList<Puesto> puestos) {
    for (Puesto p : puestos) {
      JComboPuestos.addItem(p.getNombre());
    }
  }

  @Override
  public void mostrarInfoProp(Propietario p, ArrayList<Asignacion> a) {
    if (p != null) {
      this.propietario = p;
      JNombre.setText(p.getNombreCompleto());
      mostrarTablaBonif(a);
    }
  }

  @Override
  public void error(String message) {
    JOptionPane.showMessageDialog(this, message);
  }

  private void mostrarTablaBonif(ArrayList<Asignacion> a) {
    if (a != null) {
      DefaultTableModel datos = new DefaultTableModel();
      datos.addColumn("Bonificacion");
      datos.addColumn("Puesto");
      datos.setRowCount(a.size());

      int fila = 0;

      for (Asignacion asignacion : a) {

        datos.setValueAt(asignacion.getBonificacion().getNombre(), fila, 0);
        datos.setValueAt(asignacion.getPuesto().getNombre(), fila, 1);
        fila++;
      }

      JTablaBonif.setModel(datos);
    }
  }
}
