package ui.admin;

import controladores.ControladorAsignarRecargas;
import controladores.VistaAsignarRecargas;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import logica.dominio.Administrador;
import logica.dominio.Recarga;

public class RecargasAdmin
    extends javax.swing.JDialog implements VistaAsignarRecargas {

  private ControladorAsignarRecargas controlador;

  /**
   * Creates new form AprobRecargaAdmin
   */

  public RecargasAdmin(java.awt.Frame parent, boolean modal, Administrador a) {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(null);
    this.controlador = new ControladorAsignarRecargas(this, a);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    CerrarSesionPropBtn = new javax.swing.JButton();
    jLabel18 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jLabel21 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    JListaRecargas = new javax.swing.JTable();
    CerrarSesionPropBtn1 = new javax.swing.JButton();
    jToggleButton1 = new javax.swing.JToggleButton();

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {{null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}},
        new String[] {"Title 1", "Title 2", "Title 3", "Title 4"}));
    jScrollPane1.setViewportView(jTable1);

    CerrarSesionPropBtn.setText("Cerrar sesión");

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("CONSOLA DE ADMINISTRACIÓN");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowClosed(java.awt.event.WindowEvent evt) {
        formWindowClosed(evt);
      }
      public void windowClosing(java.awt.event.WindowEvent evt) {
        formWindowClosing(evt);
      }
    });

    jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("APROBAR RECARGAS");

    jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
    jLabel1.setText("Recargas pendientes");

    jLabel21.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/img/cvu-icon.png"))); // NOI18N

    JListaRecargas.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {

        },
        new String[] {

        }));
    JListaRecargas.getTableHeader().setReorderingAllowed(false);
    jScrollPane2.setViewportView(JListaRecargas);
    JListaRecargas.getColumnModel().getSelectionModel().setSelectionMode(
        javax.swing.ListSelectionModel.SINGLE_SELECTION);

    CerrarSesionPropBtn1.setText("CERRAR");
    CerrarSesionPropBtn1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        CerrarSesionPropBtn1ActionPerformed(evt);
      }
    });

    jToggleButton1.setText("APROBAR");
    jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jToggleButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout =
        new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout.createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout
                                                    .Alignment.LEADING)
                                            .addGroup(
                                                layout.createSequentialGroup()
                                                    .addContainerGap()
                                                    .addComponent(jLabel21))
                                            .addGroup(
                                                layout.createSequentialGroup()
                                                    .addGap(50, 50, 50)
                                                    .addGroup(
                                                        layout
                                                            .createParallelGroup(
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .Alignment
                                                                    .LEADING)
                                                            .addComponent(
                                                                jLabel1)
                                                            .addGroup(
                                                                layout
                                                                    .createSequentialGroup()
                                                                    .addGap(
                                                                        6, 6, 6)
                                                                    .addGroup(
                                                                        layout
                                                                            .createParallelGroup(
                                                                                javax
                                                                                    .swing
                                                                                    .GroupLayout
                                                                                    .Alignment
                                                                                    .LEADING)
                                                                            .addComponent(
                                                                                CerrarSesionPropBtn1,
                                                                                javax
                                                                                    .swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE,
                                                                                401,
                                                                                javax
                                                                                    .swing
                                                                                    .GroupLayout
                                                                                    .PREFERRED_SIZE)
                                                                            .addGroup(
                                                                                layout
                                                                                    .createSequentialGroup()
                                                                                    .addComponent(
                                                                                        jScrollPane2,
                                                                                        javax
                                                                                            .swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE,
                                                                                        401,
                                                                                        javax
                                                                                            .swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE)
                                                                                    .addGap(
                                                                                        29,
                                                                                        29,
                                                                                        29)
                                                                                    .addComponent(
                                                                                        jToggleButton1,
                                                                                        javax
                                                                                            .swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE,
                                                                                        161,
                                                                                        javax
                                                                                            .swing
                                                                                            .GroupLayout
                                                                                            .PREFERRED_SIZE)))))))
                                    .addGap(0, 23, Short.MAX_VALUE))
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(
                                        jLabel3,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)))
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jLabel3)
                    .addGap(37, 37, 37)
                    .addComponent(jLabel1)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(
                                jScrollPane2,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 236,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(
                                jToggleButton1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addComponent(CerrarSesionPropBtn1,
                                  javax.swing.GroupLayout.PREFERRED_SIZE, 38,
                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addContainerGap()));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void CerrarSesionPropBtn1ActionPerformed(
      java.awt.event.ActionEvent
          evt) { // GEN-FIRST:event_CerrarSesionPropBtn1ActionPerformed
    controlador.salir();
    this.dispose();

  } // GEN-LAST:event_CerrarSesionPropBtn1ActionPerformed

  private void jToggleButton1ActionPerformed(
      java.awt.event
          .ActionEvent evt) { // GEN-FIRST:event_jToggleButton1ActionPerformed
    int filaSeleccionada = JListaRecargas.getSelectedRow();
    if (filaSeleccionada != -1) {
      Recarga recarga = (Recarga)JListaRecargas.getValueAt(filaSeleccionada, 2);
      controlador.aprobarRecarga(recarga);
    } // GEN-LAST:event_jToggleButton1ActionPerformed
  }

  private void formWindowClosed(
      java.awt.event.WindowEvent evt) { // GEN-FIRST:event_formWindowClosed

    controlador.salir();

  } // GEN-LAST:event_formWindowClosed

  private void formWindowClosing(
      java.awt.event.WindowEvent evt) { // GEN-FIRST:event_formWindowClosing
    // TODO add your handling code here:
  } // GEN-LAST:event_formWindowClosing

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton CerrarSesionPropBtn;
  private javax.swing.JButton CerrarSesionPropBtn1;
  private javax.swing.JTable JListaRecargas;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel18;
  private javax.swing.JLabel jLabel21;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTable1;
  private javax.swing.JToggleButton jToggleButton1;
  // End of variables declaration//GEN-END:variables

  @Override
  public void mostrarRecargas(ArrayList<Recarga> lista) {
    DefaultTableModel datos = new DefaultTableModel();
    datos.addColumn("Fecha");
    datos.addColumn("Propietario");
    datos.addColumn("Monto");

    datos.setRowCount(lista.size());

    int fila = 0;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    for (Recarga r : lista) {

      datos.setValueAt(sdf.format(r.getFecha()), fila, 0);
      datos.setValueAt(r.getPropietario().getNombreCompleto(), fila, 1);
      datos.setValueAt(r, fila, 2);
      fila = fila + 1;
    }
    JListaRecargas.setModel(datos);
  }
}
