package ui.admin;

import controladores.ControladorTransito;
import controladores.VistaTransito;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.dominio.Administrador;
import logica.dominio.Puesto;
import logica.dominio.Tarifa;
import logica.sistema.Fachada;

public class TransitoAdmin extends javax.swing.JDialog implements VistaTransito {

    private Administrador admin;
    private ControladorTransito controlador;

    /**
     * Creates new form TransitoAdmin
     */
    public TransitoAdmin(java.awt.Frame parent, boolean modal, Administrador admin) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.admin = admin;
        this.controlador = new ControladorTransito(this, this.admin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginAdmBtn3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JComboPuestos = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTablaTarifas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        JMatricula = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        LoginAdmBtn4 = new javax.swing.JButton();

        LoginAdmBtn3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        LoginAdmBtn3.setText("SALIR");
        LoginAdmBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginAdmBtn3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONSOLA DE ADMINISTRACIÓN");

        jLabel1.setText("Puestos:");

        JComboPuestos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        JComboPuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboPuestosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EMULAR TRÁNSITO");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cvu-icon.png"))); // NOI18N

        jLabel2.setText("Tarifas:");

        JTablaTarifas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTablaTarifas);

        jLabel4.setText("Ingrese Matrícula:");

        JMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMatriculaActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Registrar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        LoginAdmBtn4.setText("CERRAR");
        LoginAdmBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginAdmBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginAdmBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JComboPuestos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JComboPuestos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1)
                    .addComponent(JMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LoginAdmBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMatriculaActionPerformed

    private void LoginAdmBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginAdmBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginAdmBtn3ActionPerformed

    private void LoginAdmBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginAdmBtn4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_LoginAdmBtn4ActionPerformed

    private void JComboPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JComboPuestosActionPerformed

        Puesto puesto = (Puesto) JComboPuestos.getSelectedItem();
        controlador.cargarTarifas(puesto);

    }//GEN-LAST:event_JComboPuestosActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Puesto puesto = (Puesto) JComboPuestos.getSelectedItem();
        controlador.registrarTransito(puesto, JMatricula.getText());

    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JComboPuestos;
    private javax.swing.JTextField JMatricula;
    private javax.swing.JTable JTablaTarifas;
    private javax.swing.JButton LoginAdmBtn3;
    private javax.swing.JButton LoginAdmBtn4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void cargarPuestos(ArrayList<Puesto> puestos) {
        for (Puesto p : puestos) {
            JComboPuestos.addItem(p);
        }
    }

    @Override
    public void cargarTarifas(ArrayList<Tarifa> tarifas) {

        if (tarifas != null) {
            DefaultTableModel datos = new DefaultTableModel();
            datos.addColumn("Categoria");
            datos.addColumn("Monto");
            datos.setRowCount(tarifas.size());

            int fila = 0;

            for (Tarifa tarifa : tarifas) {

                //datos.setValueAt( i,fila, 0);
                datos.setValueAt(tarifa.getCategoria().getNombre(), fila, 0);
                datos.setValueAt(tarifa.getMonto(), fila, 1);
                fila++;
            }

            JTablaTarifas.setModel(datos);
        }
    }

    @Override
    public void error(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
}
