package ui;

public class AcercaDe extends javax.swing.JDialog {

  /**
   * Creates new form AcercaDe
   */
  public AcercaDe(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("ACERCA DE");

    jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("ESCUELA DE TECNOLOGÍA · ANALISTA PROGRAMADOR");

    jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
    jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel3.setText("DISEÑO Y DESARROLLO DE APLICACIONES");

    jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 68)); // NOI18N
    jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel4.setText("OBLIGATORIO");

    jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
    jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel5.setText("Docente: Darío Campalans");

    jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
    jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel6.setText(
        "Nicolás Fernández (147800) - Franco Pereyra (284679) - Guillermo Reboledo (204671)");

    jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
    jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel7.setText("Junio 2023");

    jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel8.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/img/logo-ort.png"))); // NOI18N

    javax.swing.GroupLayout layout =
        new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout.createSequentialGroup()
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                          Short.MAX_VALUE)
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.LEADING)
                                                  .addComponent(
                                                      jLabel4,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                                  .addComponent(
                                                      jLabel5,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                                  .addComponent(
                                                      jLabel6,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      696, Short.MAX_VALUE)
                                                  .addComponent(
                                                      jLabel7,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                                  .addComponent(
                                                      jLabel3,
                                                      javax.swing.GroupLayout
                                                          .Alignment.TRAILING,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      Short.MAX_VALUE)
                                                  .addComponent(
                                                      jLabel2,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      Short.MAX_VALUE))))
                    .addContainerGap()));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel8,
                                  javax.swing.GroupLayout.PREFERRED_SIZE, 140,
                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabel2,
                                  javax.swing.GroupLayout.PREFERRED_SIZE, 23,
                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel3)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel4,
                                  javax.swing.GroupLayout.PREFERRED_SIZE, 69,
                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)
                    .addComponent(jLabel5)
                    .addGap(32, 32, 32)
                    .addComponent(jLabel6)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel7)
                    .addContainerGap(14, Short.MAX_VALUE)));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea jTextArea1;
  // End of variables declaration//GEN-END:variables
}
